AltexFood Delivery/AltexFood Delivery/Controllers/CategoryController.cs
using System.Collections.Generic;
using AltexFood_Delivery.BLL.Services;
using AltexFood_Delivery.DAL.Interfaces;
using AltexFood_Delivery.DAL.Models;
using Microsoft.AspNetCore.Mvc;

namespace AltexFood_Delivery.Api.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class CategoryController : ControllerBase
    {
        private readonly CategoryService _categoryService;

        public CategoryController(CategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        [HttpGet]
        public IEnumerable<Category> GetCategories()
        {
            return _categoryService.GetCategories();
        }

        [HttpGet("{id}")]
        public Category GetCategory(int id)
        {
            return _categoryService.GetCategory(id);
        }

        [HttpPost]
        public IActionResult AddCategory(Category category)
        {
            var addedCategory = _categoryService.AddCategory(category);
            return addedCategory is null ? BadRequest() : Ok();
        }

        [HttpDelete]
        public IActionResult DeleteCategory(int id)
        {
            var deletedCategory = _categoryService.DeleteCategory(id);
            return deletedCategory is null ? BadRequest() : Ok();
        }

        [HttpPut]
        public IActionResult UpdateCategory(Category category)
        {
            var updatedCategory = _categoryService.UpdateCategory(category);
            return updatedCategory is null ? BadRequest() : Ok();
        }
    }
}

AltexFood Delivery/AltexFood Delivery/Controllers/ProductController.cs
using System.Collections.Generic;
using AltexFood_Delivery.BLL.Services;
using AltexFood_Delivery.DAL.Interfaces;
using AltexFood_Delivery.DAL.Models;
using Microsoft.AspNetCore.Mvc;

namespace AltexFood_Delivery.Api.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class ProductController : ControllerBase
    {
        private readonly ProductService _productService;

        public ProductController(ProductService productService)
        {
            _productService = productService;
        }

        [HttpGet]
        public IEnumerable<Product> GetProducts()
        {
            return _productService.GetProducts();
        }

        [HttpGet("{id}")]
        public Product GetProduct(int id)
        {
            return _productService.GetProduct(id);
        }

        [HttpPost]
        public IActionResult AddProduct(Product product)
        {
            var addedProduct = _productService.AddProduct(product);
            return addedProduct is null ? BadRequest() : Ok();
        }

        [HttpDelete]
        public IActionResult DeleteProduct(int id)
        {
            var deletedProduct = _productService.DeleteProduct(id);
            return deletedProduct is null ? BadRequest() : Ok();
        }

        [HttpPut]
        public IActionResult UpdateProduct(Product product)
        {
            var updatedProduct = _productService.UpdateProduct(product);
            return updatedProduct is null ? BadRequest() : Ok();
        }
    }
}

AltexFood Delivery/AltexFood Delivery/Controllers/ProductMvcController.cs
using System;
using AltexFood_Delivery.Api.Filters;
using AltexFood_Delivery.BLL.Services;
using AltexFood_Delivery.DAL.Interfaces;
using AltexFood_Delivery.DAL.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;

namespace AltexFood_Delivery.Api.Controllers
{
    [Route("mvc/Product")]
    public class ProductMvcController : Controller
    {
        private readonly ProductService _productService;
        private readonly IWebHostEnvironment _env;

        public ProductMvcController(ProductService productService, IWebHostEnvironment env)
        {
            _productService = productService;
            _env = env;
        }

        [HttpGet]
        [ServiceFilter(typeof(ConsoleLogActionFilter))]
        public IActionResult Index()
        {
            ViewBag.Dev = false;
            if (_env.IsDevelopment())
                ViewBag.Dev = true;
            return View(_productService.GetProducts());
        }

        [HttpGet("{id}")]
        [ResponseCache(Duration = 120, Location = ResponseCacheLocation.Any)]
        public IActionResult GetProduct(int id)
        {
            return View(_productService.GetProduct(id));
        }

        [HttpGet("add")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("add")]
        public IActionResult Create(Product product)
        {
            if (!ModelState.IsValid)
                return View();

            _productService.AddProduct(product);
            return RedirectToAction("Index");
        }

        [HttpGet("edit")]
        public IActionResult Edit(int id)
        {
            var product = _productService.GetProduct(id);
            if (product is not null)
                return View(product);
            return NotFound();
        }

        [HttpPost("edit")]
        public IActionResult Edit(Product product)
        {
            if (!ModelState.IsValid)
                return View();

            _productService.UpdateProduct(product);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var product = _productService.GetProduct(id);
            if (product is null)
                return NotFound();

            _productService.DeleteProduct(id);
            return RedirectToAction("Index");
        }
    }
}

AltexFood Delivery/AltexFood Delivery/Views/ProductMvc/Create.cshtml
@model Product

<form method="post" asp-action="Create">
    <div asp-validation-summary="ModelOnly"></div>
    <h2>Add Product</h2>
    
    <div>
        <section>
            <div>
                <label asp-for="Name"></label>
            </div>
            <div>
                <input asp-for="Name" />
                <span asp-validation-for="Name"></span>
            </div>
        </section>
        <section>
            <div>
                <label asp-for="Description"></label>
            </div>
            <div>
                @Html.TextAreaFor(p => p.Description, new { @rows = "5" })
            </div>
        </section>
        <section>
            <div>
                <label asp-for="Price"></label>
            </div>
            <div>
                <input type="text" id="Price" name="Price" value="0,01" />
                <span asp-validation-for="Price"></span>
            </div>
        </section>
        <section>
            <div>
                <label asp-for="AmountInStock"></label>
            </div>
            <div>
                <input asp-for="AmountInStock" />
                <span asp-validation-for="AmountInStock"></span>
            </div>
        </section>
        <section>
            <div>
                <label asp-for="CategoryId"></label>
            </div>
            <div>
                <input asp-for="CategoryId" />
            </div>
        </section>
        <section>
            <div>
                <label asp-for="SupplierId"></label>
            </div>
            <div>
                <input asp-for="SupplierId" />
            </div>
        </section>
        <section>
            <div>
                <label asp-for="Type"></label>
            </div>
            <div>
                <input asp-for="Type" />
            </div>
        </section>
    </div>
    <div>
        <input type="submit" value="Create"/>
    </div>
</form>

AltexFood Delivery/AltexFood Delivery/Views/ProductMvc/Edit.cshtml
@model Product

<form method="post">
    <div asp-validation-summary="ModelOnly"></div>
    <h2>Edit Product</h2>

    <div>
        <section>
            <div>
                <label asp-for="Name"></label>
            </div>
            <div>
                <input asp-for="Name" />
                <span asp-validation-for="Name"></span>
            </div>
        </section>
        <section>
            <div>
                <label asp-for="Description"></label>
            </div>
            <div>
                @Html.TextAreaFor(p => p.Description, new { @rows = "5" })
            </div>
        </section>
        <section>
            <div>
                <label asp-for="Price"></label>
            </div>
            <div>
                <input type="text" id="Price" name="Price" value="@Model.Price" />
                <span asp-validation-for="Price"></span>
            </div>
        </section>
        <section>
            <div>
                <label asp-for="AmountInStock"></label>
            </div>
            <div>
                <input asp-for="AmountInStock" />
                <span asp-validation-for="AmountInStock"></span>
            </div>
        </section>
        <section>
            <div>
                <label asp-for="CategoryId"></label>
            </div>
            <div>
                <input asp-for="CategoryId" />
            </div>
        </section>
        <section>
            <div>
                <label asp-for="SupplierId"></label>
            </div>
            <div>
                <input asp-for="SupplierId" />
            </div>
        </section>
        <section>
            <div>
                <label asp-for="Type"></label>
            </div>
            <div>
                <input asp-for="Type" />
            </div>
        </section>
    </div>
    <div>
        <input type="submit" value="Edit" />
    </div>
</form>

AltexFood Delivery/AltexFood Delivery/Views/ProductMvc/GetProduct.cshtml
@model Product

<div>
    <h1>@Model.Name</h1>
    <h4>@Model.Price</h4>
    <h2>@Model.Category.Name</h2>
    <h2>@Model.Supplier.Name</h2>
</div>

AltexFood Delivery/AltexFood Delivery/Views/ProductMvc/Index.cshtml
@model IEnumerable<Product>

<a asp-controller="ProductMvc" asp-action="Create">Add New Product</a>

@if (ViewBag.Dev.Equals(true))
{
<p>App is running in Development Mode</p>
}

@if (Model.Any())
{
    <table>
        <thead>
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Category</th>
            <th>Supplier</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @Html.FillProductTable(Model)
        </tbody>
    </table>
}
else
{
    <p>No products available.</p>
}

AltexFood Delivery/AltexFood Delivery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - AltexFood</title>
</head>
<body>
    <main role="main">
    @RenderBody()
    </main>
</body>
</html>